# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - 5432:5432
    
  chainlink: 
    image: smartcontract/chainlink:1.8.1-root
    ports:
      - 6688:6688
    depends_on:
      - db
    volumes:
      - ~/.chainlink-goerli:/chainlink
    env_file:
      - ~/.chainlink-goerli/.env
    command: 
      - local
      - n
      - -p 
      - /chainlink/.password 
      - -a 
      - /chainlink/.api